### ISSUE TITLE
[BUG] Wrong GreenMag ammo classname

### ISSUE THREAD

**Issue by SkippieDippie** [PulsarNeutronStar/HeartsAndMinds#2]
**Description:**
- The file /cvo/arsenal/cvo_arsenal_mod_greenmag.sqf has wrong classnames for 7.65x17 (.320ACP) ammo. (Line 14-15);
It should be `"CVO_greenmag_ammo_765x17_basic_30Rnd"` and `"CVO_greenmag_ammo_765x17_basic_60Rnd"`.

**Comment by PulsarNeutronStar** [comment]
@SkippieDippie Changed as requested. Can I tag the issue with the commit in any more meaningful way besides creating a branch etc for it?

**Comment by SkippieDippie** [comment]
@PulsarNeutronStar I'm not sure, but there is another thing. Those two ammo boxes appear in "misc." category in the arsenal instead of the custom "GreenMag" category.

**Comment by PulsarNeutronStar** [comment]
you know of a way to say "all classnames that are part of that mod" with config magic?

**Comment by PulsarNeutronStar** [comment]
9fe82efda1d8473884921d3b6215c42c1380baab
